### ISSUE TITLE
No code in current_version

### ISSUE THREAD

**Issue by davidaknowles** [rschwess/deepC#1]
Maybe forgot to add the files? 
Thanks.

**Comment by rschwess** [comment]
Sorry, I just haven't got round to comb through the scripts and replace all deprecated commands.
The tf1.8 version should run perfectly fine on any newer version bearing with some deprecation warnings. I will update and deposit the current version scripts in the next few days, but its really only going to be a command update.
Cheers

**Comment by rschwess** [comment]
Added tf1.14 version of scripts to current version. Sorry for the delay.
